index:
    path: /
    controller: App\Controller\ProductController::index
#hello_page:
#  path: /
#  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#  defaults:
#    template: 'test.html.twig'
